name: Production Deploy

on:
  push:
    branches:
      - production
  repository_dispatch:
    types: [deploy_prod]
  schedule:
    - cron:  '0 19 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
      SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      GA_ID: ${{ secrets.GA_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env:
          NODE_ENV: production
      - run: yarn run export
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: prd-pages
          force_orphan: true
